name: Deploy Server Config

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the release. Eg: 0.31.0_1735'
        required: true
      teamSize:
        description: 'Max Team Size'
        required: true
        type: choice
        options:
          - Quads
          - Duos
          - Solos
      enableBots:
        description: 'Enable Bots Backfill'
        required: false
        type: boolean
        default: false
      botsBackfillLimit:
        description: 'Add Bots Backfill Limit'
        required: true
        default: '60'

jobs:
  update_yaml:
    name: Yaml Updater
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Copy File Content
      run: cp Agones/actionRunnerConfigTemplate.yaml Agones/actionRunnerConfig.yaml
      
    - name: Replace _BUILD_NUMBER_ in yaml template
      run: sed -i "s/_BUILD_NUMBER_/${{github.event.inputs.version}}/g" Agones/actionRunnerConfig.yaml

    - name: Replace _TEAM_SIZE_ in yaml template if QUADS
      if: ${{ github.event.inputs.teamSize == 'Quads' }}
      run: sed -i "s/_TEAM_SIZE_/2/g" Agones/actionRunnerConfig.yaml
      
    - name: Replace _TEAM_SIZE_ in yaml template if DUOS
      if: ${{ github.event.inputs.teamSize == 'Duos' }}
      run: sed -i "s/_TEAM_SIZE_/1/g" Agones/actionRunnerConfig.yaml

    - name: Replace _TEAM_SIZE_ in yaml template if SOLOs
      if: ${{ github.event.inputs.teamSize == 'Solos' }}
      run: sed -i "s/_TEAM_SIZE_/0/g" Agones/actionRunnerConfig.yaml

    - name: Replace _BOTS_BACKFILL_ENABLE_ in yaml template if False
      if: ${{ github.event.inputs.enableBots == 'false' }}
      run: sed -i "s/_BOTS_BACKFILL_ENABLE_/0/g" Agones/actionRunnerConfig.yaml

    - name: Replace _BOTS_BACKFILL_ENABLE_ in yaml template if True
      if: ${{ github.event.inputs.enableBots == 'true' }}
      run: sed -i "s/_BOTS_BACKFILL_ENABLE_/1/g" Agones/actionRunnerConfig.yaml

    - name: Replace _BACKFILL_SIZE_ in yaml template
      if: ${{ github.event.inputs.enableBots == 'true' }}
      run: sed -i "s/_BACKFILL_SIZE_/${{github.event.inputs.botsBackfillLimit}}/g" Agones/actionRunnerConfig.yaml

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Agones/actionRunnerConfig.yaml
        git diff-index --quiet HEAD || git commit -m "Update config in actionRunnerConfig.yaml"
        git push

    - name: Apply the Configuration
      run: kubectl create -f https://raw.githubusercontent.com/JuneSoftware/icc/main/Agones/actionRunnerConfig.yaml
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
