name: Deploy Server Config

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the release. Eg: 0.31.0_1735'
        required: true
      teamSize:
        description: 'Max Team Size'
        required: true
        type: choice
        options:
          - unassigned
          - Solos
          - Duos
          - Quads
      enableBots:
        description: 'Enable Bots Backfill'
        required: false
        type: boolean
        default: false
      botsBackfillLimit:
        description: 'Add Bots Backfill Limit'
        required: true
        default: '60'

jobs:
  update_yaml:
    name: Yaml Updater
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: List files in main/Agones directory
      run: ls -l main/Agones/
        
    - name: Replace _BUILD_NUMBER_ in fleet.yaml
      run: sed -i "s/_BUILD_NUMBER_/${{github.event.inputs.version}}/g" Agones/actionRunnerConfig.yaml

    - name: Apply the Configuration
      run: kubectl create -f https://raw.githubusercontent.com/JuneSoftware/icc/main/Agones/actionRunnerConfig.yaml
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
