name: Deploy Server Config

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the release. Eg: 0.31.0_1735'
        required: true
      teamSize:
        description: 'Max Team Size'
        required: true
        type: choice
        options:
          - unassigned
          - Solos
          - Duos
          - Quads
      enableBots:
        description: 'Enable Bots Backfill'
        required: false
        type: boolean
        default: false
      botsBackfillLimit:
        description: 'Add Bots Backfill Limit'
        required: true
        default: '60'

jobs:
  update_yaml:
    name: Yaml Updater
    runs-on: ubuntu-latest
    steps:
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.20.0' # Specify the kubectl version you need
    - name: List Files in Repo
      run: ls -R
    - name: Update YAML file
      run: |
        python -c "import yaml; \
                   data = yaml.safe_load(open('Agones/actionRunnerConfig.yaml')); \
                   data['_BUILD_NUMBER_'] = '${{ github.event.inputs.version }}'; \
                   data['_TEAMSIZE_'] = '${{ github.event.inputs.teamSize }}'; \
                   data['_BOTSBACKFILLENABLE_'] = '${{ github.event.inputs.enableBots }}'; \
                   data['_BACKFILLSIZE_'] = '${{ github.event.inputs.botsBackfillLimit }}'; \
                   yaml.dump(data, open('Agones/actionRunnerConfig.yaml', 'w'))"

    - name: Apply the Configuration
      run: kubectl create -f https://raw.githubusercontent.com/JuneSoftware/icc/main/Agones/actionRunnerConfig.yaml
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
